name: Android CI

on:
  workflow_dispatch:

  push:
    branches: [ master, main ]
    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ master, main ]
    paths-ignore: [ '*.md' ]

  release:
    types: [ published ]

jobs:
  validation:
    name: Gradle Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  build-debug:
    needs: validation
    if: ${{ github.event_name != 'release' && needs.validation.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: local-build-debug
        uses: ./.github/actions/build-debug

  build-release:
    needs: validation
    if: ${{ github.event_name == 'release'  && needs.validation.result == 'success' && (github.event_name != 'push' || !startsWith(github.event.head_commit.message, '[skip ci]')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: local-build-release
        uses: ./.github/actions/build-release

  upload:
    name: Upload release
    runs-on: ubuntu-latest
    needs: build-release

    if: ${{ needs.build-release.result == 'success' }}

    steps:
      - uses: actions/download-artifact@v4
      - name: Build debug apk
        run: mv **/*.apk ./${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.apk
      - uses: termux/upload-release-action@v4.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.apk
          tag: ${{ github.event.release.tag_name }}
          checksums: sha256,sha512,md5